name: SonarCloud Analysis

on:
  push:
    branches:
      - main  # Change to 'main' if your default branch is main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Disable shallow clones for better analysis relevance
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed for PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
